import {set_sidebar} from '../utils/auto_sidebar.mjs'
const sidebar =  
    {
      "/js/":[
        {
          text:"介绍",
          collapsed:false,
          items:[
            {text:"前言",link:"/js/introduce/foreword.md"}
          ]
        },
        {
          text:"基础知识",
          collapsed:false,
          items:[
            {text:"常见概念",link:"/js/basicKnowledge/commonConcepts.md"},
            {text:"对象方法",link:"/js/basicKnowledge/object.md"},
            {text:"数组方法",link:"/js/basicKnowledge/array.md"},
            {text:"函数方法",link:"/js/basicKnowledge/function.md"},
            {text:"ES6",link:"/js/basicKnowledge/es6.md"},
             {text:"HTML5",link:"/js/basicKnowledge/html5.md"},
          ]
        },
        {
          text:"函数",
          collapsed:false,
          items:[
             {text:"this",link:"/js/function/this.md"},
             {text:"闭包",link:"/js/function/closure.md"},
             {text:"垃圾回收",link:"/js/function/GC.md"},
             {text:"arguments和...args",link:"/js/function/args.md"},
             {text:"防抖、节流",link:"/js/function/DebounceAndThrottle.md"},
             {text:"Promise",link:"/js/function/promise.md"},
          ]
        },
        {
          text:"常用封装",
          collapsed:false,
          items:[
            {text:"axios封装",link:"/js/commonEncapsulation/axios.md"}
          ]
        },
        {
          text:"实用方法",
          collapsed:false,
          items:[
            {text:"导出",link:"/js/practicalMethod/export.md"},
            {text:"实用js",link:"/js/practicalMethod/practicalJs.md"}
          ]
        },
        {
          text:"简便JS包",
          collapsed:true,
          items:[
            {text:"纸屑",link:"/js/greatJs/confetti.md"}
          ]
        },
        {
          text:"TS",
          collapsed:true,
          items:[
            {text:"常见情况",link:"/js/ts/commonSituations.md"}
          ]
        },
      ],
      "/jdream-plus/":{
        text:'jdream-plus',items:[
          {text:'jdream-plus',link:'/jdream-plus/'},
          {text:'button',link:'/jdream-plus/button'},
        ]
      },
      "/uni-app/":set_sidebar("/uni-app/"),
      "/vuepress/":{
        text:'vuepress',items:[
          {text:'vuepress',link:'/vuepress/'},
          {text:'vue2press快速上手',link:'/vuepress/vuepress2快速上手'},
          {text:'vuepress1注意事项',link:'/vuepress/vuepress1注意事项'},
          {text:'vuepress1组件展示插件',link:'/vuepress/vuepress1组件展示插件'},
          {text:'搜索',link:'/vuepress/搜索'},
          {text:'行号',link:'/vuepress/行号'},
          {text:'修改样式',link:'/vuepress/修改样式'},
        ]
      },
      "/vitepress/":{
          text:'vitepress',items:[
            {text:'vitepress',link:'/vitepress/'},
            {text:'快速上手',link:'/vitepress/快速上手'},
            {text:'搜索',link:'/vitepress/搜索'},
          ]
      },
      "/english/":set_sidebar("/english/"),
        //"/java/":set_sidebar("/java/"),//自动生成侧边栏，效果不佳
      "/java/":{
          text:'java',items:[
            {text:'java',link:'/java/'},
            {text:'常用cmd命令',link:'/java/常用cmd命令'},
            {text:'常用字符',link:'/java/常用字符'},
            {text:'jdk',link:'/java/jdk'},
            {text:'IDEA',link:'/java/IDEA'},
            {text:'数据类型',link:'/java/数据类型'},
            {text:'switch',link:'/java/switch'},
            {text:'常用方法',link:'/java/常用方法'},
            {text:'抽象类和接口',link:'/java/抽象类和接口'},
            {text:'easylive_study',link:'/java/easylive_study'},
          ]
      },
      "/shortcut":[
        {text:'vscdoe',link:'/shortcut/vscode'},
        {text:'chorme',link:'/shortcut/chorme'},
        {text:'markdown',link:'/shortcut/markdown'}
      ],
      "/vpcdoc/":[
       {
          text:"介绍",
          collapsed:false,
          items:[
            {text:"前言",link:"/vpcdoc/"}
          ]
        },
        {
          text:"组件",
          collapsed:false,
          items:[
            {text:"链接卡片",link:"/vpcdoc/linkCard.md"},
          ]
        },
      ],
    }



export default sidebar